---
- hosts: all
  remote_user: boscp08
  become: true
  pre_tasks:
     - shell: echo 'I":" Beginning with git '
  roles:
     - clone_socialcoin_api
  post_tasks:
     - shell: echo 'I":" Done git clone ..'