# Playbook for Database Servers
# filename: install_mysql_db_server.yml 
---
- hosts: all
  remote_user: boscp08
  become: true
  pre_tasks:
     - shell: echo 'I":" Beginning with git '
  roles:
     - install_mysql
  post_tasks:
     - shell: echo 'I":" Done git clone ..'