---
# This is a sitewide playbook 
# filename: site.yml
#boscp08@boscp08-dingo:~/.../julia$ ansible -i hosts dingofarm_workers -m ping
#ubuntuvbx | SUCCESS => {
#    "ansible_facts": {
#        "discovered_interpreter_python": "/usr/bin/python"
#    }, 
#    "changed": false, 
#    "ping": "pong"
#}
#ubuntuvmx | SUCCESS => {
#    "ansible_facts": {
#        "discovered_interpreter_python": "/usr/bin/python"
#    }, 
#    "changed": false, 
#    "ping": "pong"
#}
# ansible -i hosts dingofarm_workers -m setup | grep user
# ansible-galaxy init --init-path roles/ upd
# essentials_03_code boscp08$ ansible-galaxy init --init-path roles/ upd
# Role upd was created successfully
# cmd= ansible-playbook site.yml -i hosts -k -K
- include: apt_get_update.yml
- include: clone_socialcoin_api.yml
- include: config_socialcoin_api.yml
- include: install_mysql.yml
- include: mysql_create_db.yml
- include: mysql_import_data.yml
- include: install_nodejs_10_18_1.yml
- include: install_nvm_8_11_3.yml
- include: install_nginx_www_server.yml 
 
#boscp08@hp:~/socialcoin-api$ rm -rf node-modules
#boscp08@hp:~/socialcoin-api$ sudo npm i
#boscp08@hp:~/socialcoin-api$ npm start

#boscp08@ubuntuVMX:~$ nodejs --version
#v10.18.1
#boscp08@ubuntuVMX:~$ node --version
#v10.18.1
#boscp08@ubuntuVMX:~$ npm --version
#6.13.4
##boscp08@ubuntuVMX:~$ nvm --version
##0.33.0
## ssh  boscp08@socialcoin.westeurope.cloudapp.azure.com
## ssh  theotheu@socialcoin-api.westeurope.cloudapp.azure.com
## https://help.cloud66.com/maestro/how-to-guides/databases/shells/uninstall-mysql.html
## sudo certbot --nginx -d socialcoin-api.westeurope.cloudapp.azure.com 	2
#
#boscp08@hp:~/socialcoin-api$ rm -rf node-modules
#boscp08@hp:~/socialcoin-api$ sudo npm i
#[sudo] password for boscp08: 
#
#> sinon@4.5.0 postinstall /home/boscp08/socialcoin-api/node_modules/sinon
#> node scripts/support-sinon.js
#
#Have some ❤️ for Sinon? You can support the project via Open Collective:
# > https://opencollective.com/sinon/donate
#
#added 939 packages from 1381 contributors and audited 5564 packages in 22.401s
#found 230 vulnerabilities (25 low, 23 moderate, 181 high, 1 critical)
#  run `npm audit fix` to fix them, or `npm audit` for details
#boscp08@hp:~/socialcoin-api$ npm start
#
#> socialcoin-api@1.0.0 start /home/boscp08/socialcoin-api
#> node .
#
#Warning: detected multiple remote methods at the same HTTP endpoint. Swagger operation ids will NOT be unique.
#Web server listening at: http://127.0.0.1:3000
#Browse your REST API at http://127.0.0.1:3000/explorer