---
# This is a sitewide playbook 
# filename: site.yml
#boscp08@boscp08-dingo:~/.../julia$ ansible -i hosts dingofarm_workers -m ping
#ubuntuvbx | SUCCESS => {
#    "ansible_facts": {
#        "discovered_interpreter_python": "/usr/bin/python"
#    }, 
#    "changed": false, 
#    "ping": "pong"
#}
#ubuntuvmx | SUCCESS => {
#    "ansible_facts": {
#        "discovered_interpreter_python": "/usr/bin/python"
#    }, 
#    "changed": false, 
#    "ping": "pong"
#}

# ansible-galaxy init --init-path roles/ upd
# essentials_03_code boscp08$ ansible-galaxy init --init-path roles/ upd
# Role upd was created successfully
# cmd= ansible-playbook site.yml -i hosts -k -K
- include: apt_get_update.yml
- include: install_nginx_www_server.yml 
- include: install_nodejs_10_18_1.yml
- include: install_nvm_8_11_3.yml
- include: clone_socialcoin_api.yml
- include: install_mysql.yml
- include: mysql_create_db.yml
- include: mysql_import_data.yml
- include: config_socialcoin_api.yml 

#boscp08@ubuntuVMX:~$ nodejs --version
#v10.18.1
#boscp08@ubuntuVMX:~$ node --version
#v10.18.1
#boscp08@ubuntuVMX:~$ npm --version
#6.13.4
#boscp08@ubuntuVMX:~$ nvm --version
#0.33.0
