---
#- name: add official nginx repository
#  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ lucid nginx'
# - name: install nginx web server and ensure its at the latest version
#   apt: name=nginx state=latest force=yes

- name: install nginx
  become: yes
  become_method: sudo
  apt: name=nginx state=latest
    
- name: Copy nginx file
  template: src=default.conf dest=/etc/nginx/sites-enabled/default
  notify: 
    - restart nginx service

