- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Write root login credentials
  copy:
     dest: /root/.my.cnf
     owner: root
     group: root
     mode: 0600
     content: |
         [client]
         user=root
         password="{{ mysql_root_password }}"

  #https://github.com/ansible/ansible/issues/47736
- name: Ensure mysql root password is updated for all root accounts 
  mysql_user:
    name: root
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql_root_password }}"   #Nw
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  become: yes
  #notify: Restart MySQL
 
- name:  Grant access by editing /etc/mysql/mysql.conf.d/mysqld.cnf
  replace:
    #path: /etc/mysql/mysql.conf.d/mysqld.cnf
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: 'bind-address'
    replace: '# bind-address  Ansible Grant access by editing '

- name: Create new databases with names 'socialcoin' and 'security'
  mysql_db:
    name:
      - security
      - socialcoin
    state: present    
  become: true

- name: Create database user <<username>> with name '<<username>>' and password '********' with all database privileges
  mysql_user:
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL,GRANT'
    state: present   
  