---

 - name: Edit ~/socialcoin/socialcoin-api/server/datasources.json and paste
   copy: src=socialcoin_api_server_datasources.json dest=/home/boscp08/socialcoin-api/server/datasources.json
    
 - name: Edit ~/socialcoin/socialcoin-api/server/config.json and paste
   copy: src=socialcoin_api_server_config.json dest=/home/boscp08/socialcoin-api/server/config.json

 - name: Edit ~/socialcoin/socialcoin-api/server/middleware.json and paste
   copy: src=socialcoin_api_server_middleware.json dest=/home/boscp08/socialcoin-api/server/middleware.json


 - name: Remove directory /home/boscp08/socialcoin-api/server  rm -rf /home/boscp08/socialcoin-api/node-modules
   file:
      path: /home/boscp08/socialcoin-api/node-modules
      state: absent

 - name: This npm i command will change the working directory to /home/boscp08/socialcoin-api/ /.
   shell:
      cmd: npm i
      chdir: /home/boscp08/socialcoin-api/