---

 - name: Edit ~/socialcoin/socialcoin-api/server/datasources.json and paste
   copy: src=socialcoin_api_server_datasources.json dest=/home/boscp08/socialcoin-api/server/datasources.json
    
 - name: Edit ~/socialcoin/socialcoin-api/server/config.json and paste
   copy: src=socialcoin_api_server_config.json dest=/home/boscp08/socialcoin-api/server/config.json

 - name: Edit ~/socialcoin/socialcoin-api/server/middleware.json and paste
   copy: src=socialcoin_api_server_middleware.json dest=/home/boscp08/socialcoin-api/server/middleware.json


