---

  - name: Ensure mysql is running and starts on boot
    service:
      name: mysql
      state: started
      enabled: yes
    become: yes
  
#  - name: Create new databases with names 'foo' and 'bar'
#    mysql_db:
#      name:
#        - foo
#        - bar
#      state: present    
#    become: true
#
  - name: Create new databases with names 'socialcoin' and 'security'
    mysql_db:
      name:
        - security
        - socialcoin
      state: present    
    become: true


# Restart MySQL
#- name: Restart MySQL
#  command: /bin/true
#  notify:
#    - Restart MySQL
#  tags:
#    - mysql

