---

  - name: Ensure mysql is running and starts on boot
    service:
      name: mysql
      state: started
      enabled: yes
    become: yes
  
  - name: Create new databases with names 'socialcoin' and 'security'
    mysql_db:
      name:
        - security
        - socialcoin
      state: present    
    become: true


  - name: Create database user socialcoinAdmin with name 'socialcoinAdmin' and password '12345' with all database privileges
    mysql_user:
      name: socialcoinAdmin
      password: Discipl_Socialcoin2020
      priv: '*.*:ALL'
      state: present    

  - name: Create database user theotheu with name 'socialcoinAdmin' and password '12345' with all database privileges
    mysql_user:
      name: theotheu
      password: theotheu
      priv: '*.*:ALL,GRANT'
      state: present        


