---
# filename: roles/mysql/tasks/install_Debian.yml

  - name: install mysql server
    apt: 
      name: "{{ mysql_pkg }}" 
      update_cache: yes

  - name: mysql-client
    apt:
      name:
        - mysql-client
      state: latest
      cache_valid_time: 3600    # update cache if more than an hour old

           
#
  - name: python-pymysql
    apt:
      name:
        - python-pymysql
      state: latest
      cache_valid_time: 3600    # update cache if more than an hour old
# rationale 20200202 fatal: [ubuntuvbx2]: FAILED! => {"changed": false, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}       

 
# Write password to root home as readable only by root so future mysql
# operations can function.
  - name: Write root login credentials
    copy:
       dest: /root/.my.cnf
       owner: root
       group: root
       mode: 0600
       content: |
           [client]
           user=root
           password=Discipl_Socialcoin2020
#https://github.com/ansible/ansible/issues/47736

  - name: Ensure mysql root password is updated for all root accounts
    mysql_user:
      name: root
      host: localhost
      login_unix_socket: /var/run/mysqld/mysqld.sock
      password: Discipl_Socialcoin2020
      priv: '*.*:ALL,GRANT'
      check_implicit_admin: true
    become: yes
    #notify: Restart MySQL

  - name:  Grant access by editing /etc/mysql/mysql.conf.d/mysqld.cnf
    replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: 'bind-address'
      replace: '# bind-address  Ansible Grant access by editing '

