---
# filename: roles/mysql/tasks/install_Debian.yml

  - name: install mysql server
    apt: 
      name: "{{ mysql_pkg }}" 
      update_cache: yes

  - name: mysql-client
    apt:
      name:
        - mysql-client
      state: latest
      cache_valid_time: 3600    # update cache if more than an hour old

           
#
 

