--- 
  - name: "curl -o /tmp/2020-01-17.security.sql "
    shell: curl -o /tmp/2020-01-17.security.sql https://raw.githubusercontent.com/boschpeter/theotheu/master/theotheu/2020-01-17.security.sql

  - name: "curl -o /tmp/2020-01-17.socialcoin.sql"
    shell: curl -o /tmp/2020-01-17.socialcoin.sql https://raw.githubusercontent.com/boschpeter/theotheu/master/theotheu/2020-01-17.socialcoin.sql
    
  - name: Import 2020-01-17.security.sql similar to mysql -u <username> -p <password> < hostname.sql
    mysql_db: 
     state: import
     name: security
     target: /tmp/2020-01-17.security.sql

  - name: Import 2020-01-17.socialcoin.sql similar to mysql -u <username> -p <password> < hostname.sql
    mysql_db: 
     state: import
     name: socialcoin
     target: /tmp/2020-01-17.socialcoin.sql

  
