---
#- name: ansible remove directory /home/boscp08
#  file:
#      path: /home/boscp08/
#      state: absent

#- name: Create Project Directory /home/boscp08
#  file: path=/home/boscp08 state=directory

#- name: Git Clone github Repo command
#  raw:  git clone https://gitlab.com/socialcoin/socialcoin-api.git
#  args:
#     chdir:  /home/boscp08/

- name: Git Clone github Repo command
  command:  git clone https://github.com/boschpeter/socialcoin-api.git
  args:
     chdir:  /home/boscp08

